package com.coderedrobotics.dashboard.api.gui;

import com.coderedrobotics.dashboard.api.resources.RemoteString;
import com.coderedrobotics.dashboard.api.resources.listeners.RemoteStringListener;
import com.coderedrobotics.dashboard.communications.Connection;
import com.coderedrobotics.dashboard.communications.Subsocket;
import com.coderedrobotics.dashboard.communications.exceptions.InvalidRouteException;
import com.coderedrobotics.dashboard.communications.exceptions.NotMultiplexedException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Michael
 */
public class StatusLabel extends javax.swing.JPanel implements RemoteStringListener {

    RemoteString value;
    
    /**
     * Creates new form StatusLabel
     */
    public StatusLabel() {
        initComponents();
    }
    
    public void setup(String subsocketPath) {
        try {
            Subsocket root = Connection.getInstance().getRootSubsocket().enableMultiplexing();
            root.createNewRoute(subsocketPath).enableMultiplexing();
            value = new RemoteString(subsocketPath, RemoteString.MODE.LOCAL);
            value.addListener(this);
        } catch (InvalidRouteException | NotMultiplexedException ex) {
            Logger.getLogger(StatusLabel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setText(String text) {
        jLabel1.setText(text);
    }
    
    @Override
    public void update(String string, RemoteString sender) {
        setText(string);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}