/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package robotgui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import share.DataStreamingModule;
import share.SynchronizedRegisterArray;

/**
 *
 * @author laptop
 */
public class MainWindow extends javax.swing.JFrame {

    DataStreamingModule dataStreamingModule;
    SynchronizedRegisterArray synchronizedRegisterArray;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setSize(1024, 350);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        terminalTab = new robotgui.Terminal();
        pWMandDIO1 = new robotgui.PWMandDIO();
        pID1 = new robotgui.PID();
        sRAandDSM1 = new robotgui.SRAandDSM();
        cAN1 = new robotgui.CAN();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabbedPane.addTab("Terminal", terminalTab);
        tabbedPane.addTab("PWM and DIO", pWMandDIO1);
        tabbedPane.addTab("PID", pID1);
        tabbedPane.addTab("SRA and DSM", sRAandDSM1);
        tabbedPane.addTab("CAN", cAN1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 321, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private robotgui.CAN cAN1;
    private robotgui.PID pID1;
    private robotgui.PWMandDIO pWMandDIO1;
    private robotgui.SRAandDSM sRAandDSM1;
    private javax.swing.JTabbedPane tabbedPane;
    private robotgui.Terminal terminalTab;
    // End of variables declaration//GEN-END:variables

    void init(DataStreamingModule dataStreamingModule,
            SynchronizedRegisterArray synchronizedRegisterArray) {
        this.dataStreamingModule = dataStreamingModule;
        this.synchronizedRegisterArray = synchronizedRegisterArray;
        pWMandDIO1.init(dataStreamingModule, synchronizedRegisterArray);
        pID1.init(dataStreamingModule, synchronizedRegisterArray);
        sRAandDSM1.init(synchronizedRegisterArray, dataStreamingModule);
    }
}
