/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package robotgui;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import share.DataStream;
import share.DataStreamingModule;
import share.SynchronizedRegisterArray;

/**
 *
 * @author laptop
 */
public class PWMandDIO extends javax.swing.JPanel implements Runnable{

    DataStreamingModule dataStreamingModule;
    SynchronizedRegisterArray synchronizedRegisterArray;
    Thread thread;

    /**
     * Creates new form PWMandDIO
     */
    public PWMandDIO() {
        initComponents();
        thread = new Thread(this);
        thread.start();
    }
    
    @Override
    public void run() {
        while (true) {            
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(PWMandDIO.class.getName()).log(Level.SEVERE, null, ex);
            }
            refresh();
        }
    }

    public void init(DataStreamingModule dataStreamingModule,
            SynchronizedRegisterArray synchronizedRegisterArray) {
        this.dataStreamingModule = dataStreamingModule;
        this.synchronizedRegisterArray = synchronizedRegisterArray;
    }

    public void refresh() {
        if (dataStreamingModule != null) {
            for (int i = 0; i < 10; i++) {
                DataStream dataStream =
                        dataStreamingModule.getStream("PWM" + i);
                if (dataStream != null) {
                    iOpanel1.setPWM(i, dataStream.getLastPacket().val);
                }
            }
            for (int i = 0; i < 14; i++) {
                DataStream dataStreamD =
                        dataStreamingModule.getStream("DIOD" + i);
                DataStream dataStreamS =
                        dataStreamingModule.getStream("DIOS" + i);
                if (dataStreamD != null && dataStreamS != null) {
                    iOpanel1.setDIO(i,
                            dataStreamD.getLastPacket().val == 1,
                            dataStreamS.getLastPacket().val == 1);
                }
            }
            for (int i = 0; i < 8; i++) {
                DataStream dataStreamF =
                        dataStreamingModule.getStream("RelayF" + i);
                DataStream dataStreamR =
                        dataStreamingModule.getStream("RelayR" + i);
                if (dataStreamF != null && dataStreamR != null) {
                    iOpanel1.setRelay(i,
                            dataStreamF.getLastPacket().val == 1,
                            dataStreamR.getLastPacket().val == 1);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graph1 = new robotgui.Graph();
        iOpanel1 = new robotgui.IOpanel();
        jComboBox1 = new javax.swing.JComboBox();

        javax.swing.GroupLayout graph1Layout = new javax.swing.GroupLayout(graph1);
        graph1.setLayout(graph1Layout);
        graph1Layout.setHorizontalGroup(
            graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graph1Layout.setVerticalGroup(
            graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PWM1", "PWM2", "PWM3", "PWM4", "PWM5", "PWM6", "PWM7", "PWM8", "PWM9", "PWM10", "DIO1-7", "DIO8-14", "Relays" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graph1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, 408, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iOpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iOpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graph1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int selection = jComboBox1.getSelectedIndex();
        if (dataStreamingModule != null) {
            if (selection > -1 && selection < 10
                    && dataStreamingModule.getStream(
                    "PWM" + selection) != null) {
                graph1.removeAllStreams();
                graph1.addStream(
                        dataStreamingModule.getStream("PWM" + selection),
                        Color.GREEN, 0, 1, false);
                return;
            }
            if (selection == 10) {
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private robotgui.Graph graph1;
    private robotgui.IOpanel iOpanel1;
    private javax.swing.JComboBox jComboBox1;
    // End of variables declaration//GEN-END:variables
}
