package com.coderedrobotics.dashboard.dashboard;

import java.awt.Component;

/**
 * JFrame form for dashboard. This is basically an empty container, and tabs are
 * added to a jTabbedPane when new plugins are loaded. This class also calls {@link
 * com.coderedrobotics.dashboard.Main#unloadPlugins()
 * Main.unloadPlugins()}.
 *
 * @author Michael
 */
class MainGUI extends javax.swing.JFrame {

    PluginsInfo pinfo;

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        this.setLocation(0, 0);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                Debug.println("[API] Shutting down...", Debug.STANDARD);
                Start.unloadPlugins();
                Debug.println("[API] Plugin unloading complete.\n[API] Exiting...", Debug.STANDARD);
            }
        });
        pinfo = new PluginsInfo();
        tabs.addTab("Installed Plugins", pinfo);
    }

    /**
     * Creates a new tab with title and component set by loaded plugin.
     *
     * @param title Sets the title of the new tab added.
     * @param comp Sets the component inside the new tab.
     */
    void addPluginGUI(String title, Component comp) {
        tabs.addTab(title, comp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Code Red Robotics Dashboard");
        setMinimumSize(new java.awt.Dimension(1024, 400));
        setName("jFrame"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 400));

        tabs.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
