package com.coderedrobotics.dashboard.dashboard;

import com.coderedrobotics.dashboard.communications.Connection;
import java.awt.Component;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import javax.swing.JOptionPane;

/**
 * JFrame form for dashboard. This is basically an empty container, and tabs are
 * added to a jTabbedPane when new plugins are loaded. This class also calls {@link
 * com.coderedrobotics.dashboard.Main#unloadPlugins()
 * Main.unloadPlugins()}.
 *
 * @author Michael
 */
class MainGUI extends javax.swing.JFrame {

    OptionsContainer container;
    private boolean snap = false;

    /**
     * Creates new form MainGUI
     */
    MainGUI() {
        initComponents();
        dispose();
        this.setLocation(0, 0);

        setupCloseListener();

        container = new OptionsContainer();
        container.init(this);
    }

    /**
     * Creates a new tab with title and component set by loaded plugin.
     *
     * @param title Sets the title of the new tab added.
     * @param comp Sets the component inside the new tab.
     */
    void addPluginGUI(String title, Component comp) {
        tabs.addTab(title, comp);
    }

    void setOpenTab(int i) {
        tabs.setSelectedIndex(i);
    }

    void setSnap(boolean snap) {
        this.snap = snap;
    }

    @Override
    public void setVisible(boolean b) {
        if (b) {
            if (snap) {
                setUndecorated(true);
                setSize(1024, 400);
                setMinimumSize(new java.awt.Dimension(1024, 400));
                setResizable(false);
                setLocation(0, 0);
            } else {
                setUndecorated(false);
                setSize(1059, 435);
                setMinimumSize(new java.awt.Dimension(1059, 435));
                setResizable(true);
                //<editor-fold defaultstate="collapsed" desc="Center to Screen">
                GraphicsEnvironment g = GraphicsEnvironment.getLocalGraphicsEnvironment();
                GraphicsDevice[] devices = g.getScreenDevices();

                int width = devices[0].getDisplayMode().getWidth();
                int height = devices[0].getDisplayMode().getHeight();

                int w = this.getSize().width;
                int h = this.getSize().height;

                int x = (width - w) / 2;
                int y = (height - h) / 2;
                this.setLocation(x, y);
                //</editor-fold>
            }
            super.setVisible(b);
        } else {
            dispose();
        }
    }

    OptionsContainer getOptionsContainer() {
        return container;
    }

    private void setupCloseListener() {
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            MainGUI gui;

            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                int close = JOptionPane.showConfirmDialog(gui, "Are you sure you want to close?", "Confirm Close", JOptionPane.YES_NO_OPTION);
                if (close == 0) {
                    Debug.println("[API] Shutting down...", Debug.STANDARD);
                    Connection.getInstance().disconnect();
                    Data.getInstance().writeMemory();
                    Start.unloadPlugins();
                    Debug.println("[API] Plugin unloading complete.\n[API] Exiting...", Debug.STANDARD);
                    System.exit(0);
                }
            }

            public java.awt.event.WindowAdapter init(MainGUI gui) {
                this.gui = gui;
                return this;
            }
        }.init(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Code Red Robotics Dashboard");
        setMaximumSize(new java.awt.Dimension(1024, 400));
        setMinimumSize(new java.awt.Dimension(1024, 400));
        setName("jFrame"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        tabs.setBackground(new java.awt.Color(43, 43, 43));
        tabs.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
