package com.coderedrobotics.dashboard.dashboard;

import java.awt.CardLayout;

/**
 *
 * @author Michael
 */
public class OptionsContainer extends javax.swing.JPanel {

    MainGUI gui;

    /**
     * Creates new form OptionsContainer
     */
    public OptionsContainer() {
        initComponents();
    }

    void init(MainGUI gui) {
        optionsPanel.init(this);
        pluginInfoPanel.init(this);
        this.gui = gui;
    }

    Options getOptionsPanel() {
        return optionsPanel;
    }

    PluginsInfo getPluginsInfoPanel() {
        return pluginInfoPanel;
    }

    MainGUI getMainGUI() {
        return gui;
    }
    
    void switchToPluginInfo() {
        CardLayout cl = (CardLayout) (getLayout());
        cl.show(this, "pluginsInfo");
    }
    
    void switchToOptions() {
        CardLayout cl = (CardLayout) (getLayout());
        cl.show(this, "Options");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsPanel = new com.coderedrobotics.dashboard.dashboard.Options();
        pluginInfoPanel = new com.coderedrobotics.dashboard.dashboard.PluginsInfo();

        setLayout(new java.awt.CardLayout());
        add(optionsPanel, "Options");
        add(pluginInfoPanel, "pluginsInfo");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.coderedrobotics.dashboard.dashboard.Options optionsPanel;
    private com.coderedrobotics.dashboard.dashboard.PluginsInfo pluginInfoPanel;
    // End of variables declaration//GEN-END:variables

}
